<?php 

 return [
    "content" =>'<span><h3>Coin Introduction</h3>
   <p>Bit coin is the first virtual currency implemented. Using P2P network technology, users participating in the network independently issue currency and manage the contents of the transfer without a central authority or intermediary managing the issuance and distribution. Bitcoin is the first coin to introduce a block-chain technology that makes this possible. 
   The number of individuals and businesses using Bitcoin is steadily increasing, including retailers, including restaurants, apartments, law firms and online services. Bitcoin is a new social phenomenon, but it is growing very quickly. As a result, millions of dollars of bit coins are exchanged every day, as well as increasing value. Bitcoin is the largest market value and coin value in the virtual currency market, and trading volume is also stable. Etherium is fast catching up, but it is still the most robust virtual currency.</p>
<h3>Coin feature</h3>
    <p> 1. Bitcoin\'s operating system, where transactions can be managed by users without a central entity, is due to block-chain technology. Block chains are easily operated by sharing the books together and always comparing the book files on each other\'s computers to the same content. Thus, security is achieved through the opposite operation that traditional financial institutions have firmly defended against their books. To hack a book, 51% of the books must be manipulated at the same time, which is virtually impossible. Because it takes enormous computing power to do this, and supercomputers that can do this do not exist in the world. In addition, book data is stored in blocks in the form of a cryptographic hash function, rather than being recorded as juggles, and these blocks are linked together to provide greater security. 
     2. The bit coin issues a new coin in a manner that pays the block issuer compensation to the miners. Block issue reimbursement is reduced by half based on 210,000 blocks (approximately 4 years). At first it was issued with 50-bit coins, and it has been decreasing by half every four years. Once the total amount of coins reaches 21 million, new issuance will be terminated and the system will be supported only through transaction fees thereafter.</p>
<h3>Core value</h3>
(Keyword: universality and convenience that can be used in currency) 
 <p>1. Prior to the appearance of various Altcoins, Bitcoin is now the most common form of payment because it is unique in the virtual currency market. In addition to being overwhelmingly bigger than Altcoins in real life, this is also increasing. For example, Japanese companies will soon be able to use Bitcoin at 260,000 off-line stores as soon as they introduce a bit coin billing system. 2. In many countries, while recognizing bit coin as a formal payment method, it is said that there is no added value tax when trading real money and virtual money. Indeed, in Japan and Australia, Bitcoin has already been accepted as a legitimate payment instrument and has been brought into the system. In the US, Bitcoin ETF approval efforts are underway. It is said that an ATM machine based on bit coin is also installed in each country.</p>
    </span>'];